import { BiEnvelope } from "react-icons/bi";
import { GrStackOverflow } from "react-icons/gr";
import { AiOutlineAppstore } from "react-icons/ai";
import {
  FaEye,
  FaEyeSlash,
  FaFacebookF,
  FaGithub,
  FaHeart,
  FaHouseUser,
  FaInstagram,
  FaLaptopCode,
  FaLinkedinIn,
  FaMediumM,
  FaRegHeart,
  FaTwitter,
} from "react-icons/fa";
import {
  FiBell,
  FiBookmark,
  FiCamera,
  FiEdit3,
  FiImage,
  FiLink2,
  FiLock,
  FiMenu,
  FiMessageCircle,
  FiMessageSquare,
  FiMoreHorizontal,
  FiMoreVertical,
  FiSearch,
  FiSettings,
  FiTrash2,
  FiUser,
  FiUserCheck,
  FiUserPlus,
  FiUsers,
  FiUserX,
  FiX,
} from "react-icons/fi";

export {
  /****** UTILITY ******/
  AiOutlineAppstore as Apps,
  BiEnvelope as Message,
  FaEye as Eye,
  FaEyeSlash as EyeOff,
  FaHouseUser as House,
  FaLaptopCode as Laptop,
  FaRegHeart as Like,
  FiBell as Notification,
  FiBookmark as Bookmark,
  FiCamera as Camera,
  FiEdit3 as Pencil,
  FiImage as Image,
  FiLink2 as Link,
  FiLock as Lock,
  FiMenu as Menu,
  FiMessageCircle as Comment,
  FiMessageSquare as Chat,
  FiMoreHorizontal as Hmenu,
  FiMoreVertical as Vmenu,
  FiSearch as Search,
  FiSettings as Settings,
  FiTrash2 as Delete,
  FiUser as User,
  FiUserCheck as AddedFriend,
  FiUserPlus as AddFriend,
  FiUsers as Users,
  FiUserX as RemoveFriend,
  FiX as Close,
  GrStackOverflow as Stack,

  /****** SOLID ******/
  FaHeart as Liked,
  
  /****** BRANDS ******/
  FaFacebookF as Facebook,
  FaGithub as Github,
  FaInstagram as Instagram,
  FaLinkedinIn as LinkedIn,
  FaMediumM as Medium,
  FaTwitter as Twitter,
};
